site_name: Vagahbond's NixOS configuration options
site_description: A generated documentation for options I created in my Nixos configuration.
site_url: https://vagahbond.github.io/nix-config/
repo_url: https://github.com/Vagahbond/nix-config
site_author: Vagahbond

nav:
  - Home: index.md

theme:
  name: material

  include_sidebar: false
