name: "Build"
on:
  pull_request:
    paths:
      - "**/*.nix"
  push:
    branches:
      - master
    paths:
      - "**/*.nix"
jobs:
  tests:
    name: Check that flake builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
